#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "expression_parser.y".
#

require "racc/parser"
module ApiQueryLanguage
  module Sorting
    class ExpressionParser < Racc::Parser
      module_eval(<<'...END EXPRESSION_PARSER.Y/MODULE_EVAL...', __FILE__, __LINE__ + 1)
  include ApiQueryLanguage::ExpressionParserHelper
  include ApiQueryLanguage::Sorting::SortParserHelper
...END EXPRESSION_PARSER.Y/MODULE_EVAL...
      ##### State transition tables begin ###

      racc_action_table = [
        6, 7, 8, 9, 10, 11, 6, 6
      ]

      racc_action_check = [
        0, 1, 3, 4, 6, 7, 8, 10
      ]

      racc_action_pointer = [
        -4, 1, nil, 0, 0, nil, -1, 5, 2, nil,
        3, nil, nil, nil
      ]

      racc_action_default = [
        -8, -8, -1, -3, -8, -5, -7, -8, -8, -4,
        -8, 14, -2, -6
      ]

      racc_goto_table = [
        1, 13, nil, nil, nil, nil, nil, nil, 12
      ]

      racc_goto_check = [
        1, 4, nil, nil, nil, nil, nil, nil, 1
      ]

      racc_goto_pointer = [
        nil, 0, nil, nil, -9, nil
      ]

      racc_goto_default = [
        nil, nil, 2, 3, 4, 5
      ]

      racc_reduce_table = [
        0, 0, :racc_error,
        1, 7, :_reduce_none,
        3, 8, :_reduce_2,
        1, 8, :_reduce_3,
        2, 9, :_reduce_4,
        1, 10, :_reduce_none,
        3, 11, :_reduce_6,
        1, 11, :_reduce_7
      ]

      racc_reduce_n = 8

      racc_shift_n = 14

      racc_token_table = {
        false => 0,
        :error => 1,
        :SORT_SEPARATOR => 2,
        :DIRECTION_OPERATOR => 3,
        :FIELD_IDENTIFIER => 4,
        :FIELD_IDENTIFIER_SEPARATOR => 5
      }

      racc_nt_base = 6

      racc_use_result_var = false

      Racc_arg = [
        racc_action_table,
        racc_action_check,
        racc_action_default,
        racc_action_pointer,
        racc_goto_table,
        racc_goto_check,
        racc_goto_default,
        racc_goto_pointer,
        racc_nt_base,
        racc_reduce_table,
        racc_token_table,
        racc_shift_n,
        racc_reduce_n,
        racc_use_result_var
      ]
      Ractor.make_shareable(Racc_arg) if defined?(Ractor)

      Racc_token_to_s_table = [
        "$end",
        "error",
        "SORT_SEPARATOR",
        "DIRECTION_OPERATOR",
        "FIELD_IDENTIFIER",
        "FIELD_IDENTIFIER_SEPARATOR",
        "$start",
        "expression",
        "sorts",
        "sort",
        "field_expression",
        "fields"
      ]
      Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

      Racc_debug_parser = false

      ##### State transition tables end #####

      # reduce 0 omitted

      # reduce 1 omitted

      module_eval(<<'.,.,', __FILE__, __LINE__ + 1)
  def _reduce_2(val, _values)
     parse_join_sort_expression(val)
  end
.,.,

      module_eval(<<'.,.,', __FILE__, __LINE__ + 1)
  def _reduce_3(val, _values)
     parse_single_sort_expression(val)
  end
.,.,

      module_eval(<<'.,.,', __FILE__, __LINE__ + 1)
  def _reduce_4(val, _values)
     parse_field_sort(val)
  end
.,.,

      # reduce 5 omitted

      module_eval(<<'.,.,', __FILE__, __LINE__ + 1)
  def _reduce_6(val, _values)
     parse_field(val)
  end
.,.,

      module_eval(<<'.,.,', __FILE__, __LINE__ + 1)
  def _reduce_7(val, _values)
     parse_field(val)
  end
.,.,

      def _reduce_none(val, _values)
        val[0]
      end
    end   # class ExpressionParser
  end   # module Sorting
end   # module ApiQueryLanguage
