# frozen_string_literal: true

#--
# This file is automatically generated. Do not modify it.
# Generated by: oedipus_lex version 2.6.2.
# Source: app/lib/sorting/expression_lexer.rex
#++

# Regenerate with `bundle exec rake generate` from api_query_language/.

##
# The generated lexer ApiQueryLanguage::Sorting::ExpressionLexer

class ApiQueryLanguage::Sorting::ExpressionLexer
  require "strscan"

  # :stopdoc:
  FIELD_IDENTIFIER = /[A-Za-z][0-9A-Za-z_-]+/
  DIRECTION_OPERATOR = /asc|desc/
  # :startdoc:
  # :stopdoc:
  class LexerError < StandardError; end
  class ScanError < LexerError; end
  # :startdoc:

  ##
  # The file name / path

  attr_accessor :filename

  ##
  # The StringScanner for this lexer.

  attr_accessor :ss

  ##
  # The current lexical state.

  attr_accessor :state

  alias_method :match, :ss

  ##
  # The match groups for the current scan.

  def matches
    m = (1..9).map { |i| ss[i] }
    m.pop until m[-1] or m.empty?
    m
  end

  ##
  # Yields on the current action.

  def action
    yield
  end

  ##
  # The current scanner class. Must be overridden in subclasses.

  unless instance_methods(false).map(&:to_s).include?("scanner_class")
    def scanner_class
      StringScanner
    end
  end

  ##
  # Parse the given string.

  def parse str
    self.ss = scanner_class.new str
    self.state ||= nil

    do_parse
  end

  ##
  # Read in and parse the file at +path+.

  def parse_file path
    self.filename = path
    open path do |f|
      parse f.read
    end
  end

  ##
  # The current location in the parse.

  def location
    [
      filename || "<input>"
    ].compact.join(":")
  end

  ##
  # Lex the next token.

  def next_token
    token = nil

    until ss.eos? or token
      token =
        case state
        when nil
          if text = ss.scan(/#{FIELD_IDENTIFIER}/o)

            action { [:FIELD_IDENTIFIER, text] }
          elsif ss.skip(/:(#{DIRECTION_OPERATOR})/o)

            action { [:DIRECTION_OPERATOR, matches[0]] }
          elsif text = ss.scan(".")

            action { [:FIELD_IDENTIFIER_SEPARATOR, text] }
          elsif text = ss.scan(";")

            action { [:SORT_SEPARATOR, text] }
          elsif ss.skip(/\s+/)

            # do nothing
          else
            text = ss.string[ss.pos..-1]
            raise ScanError, "can not match (#{state.inspect}) at #{location}: '#{text}'"
          end
        else
          raise ScanError, "undefined state at #{location}: '#{state}'"
        end # token = case state

      next unless token # allow functions to trigger redo w/ nil
    end # while

    raise LexerError, "bad lexical result at #{location}: #{token.inspect}" unless
      token.nil? || (Array === token && token.size >= 2)

    # auto-switch state
    self.state = token.last if token && token.first == :state

    token
  end # def next_token

  def parse(str, parser)
    self.ss = scanner_class.new str
    self.state ||= nil
    parser.do_parse
  end
end # class
