#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "expression_parser.y".
#

require "racc/parser"
module ApiQueryLanguage
  module Filtering
    class ExpressionParser < Racc::Parser
      module_eval(<<'...END EXPRESSION_PARSER.Y/MODULE_EVAL...', __FILE__, __LINE__ + 1)
  include ApiQueryLanguage::ExpressionParserHelper
  include ApiQueryLanguage::Filtering::FilterParserHelper
...END EXPRESSION_PARSER.Y/MODULE_EVAL...
      ##### State transition tables begin ###

      racc_action_table = [
        5, 6, 11, 7, 12, 8, 9, 5, 6, 25,
        7, 24, 8, 9, 5, 6, 10, 7, 15, 8,
        9, 5, 6, 20, 7, 23, 8, 9, 6, 26,
        7, 18, 8, 9, 19, 18, 18, 27, 19, 19,
        30
      ]

      racc_action_check = [
        0, 0, 4, 0, 4, 0, 0, 6, 6, 17,
        6, 17, 6, 6, 11, 11, 1, 11, 7, 11,
        11, 12, 12, 10, 12, 14, 12, 12, 5, 18,
        5, 8, 5, 5, 8, 24, 25, 19, 24, 25,
        27
      ]

      racc_action_pointer = [
        -6, 16, nil, nil, 0, 21, 1, 8, 21, nil,
        23, 8, 15, nil, 17, nil, nil, 6, 16, 27,
        nil, nil, nil, nil, 25, 26, nil, 27, nil, nil,
        nil
      ]

      racc_action_default = [
        -18, -18, -1, -2, -6, -18, -18, -18, -18, -10,
        -18, -18, -18, -5, -18, -8, -9, -13, -14, -18,
        31, -3, -4, -7, -18, -18, -16, -15, -11, -12,
        -17
      ]

      racc_goto_table = [
        16, 2, 1, 14, 13, nil, nil, nil, nil, nil,
        nil, nil, 21, 22, nil, nil, 28, 29
      ]

      racc_goto_check = [
        5, 2, 1, 3, 4, nil, nil, nil, nil, nil,
        nil, nil, 2, 2, nil, nil, 5, 5
      ]

      racc_goto_pointer = [
        nil, 2, 1, -3, -1, -8, nil
      ]

      racc_goto_default = [
        nil, nil, nil, 3, 4, nil, 17
      ]

      racc_reduce_table = [
        0, 0, :racc_error,
        1, 15, :_reduce_1,
        1, 16, :_reduce_none,
        3, 17, :_reduce_3,
        3, 17, :_reduce_4,
        2, 17, :_reduce_5,
        1, 17, :_reduce_6,
        3, 18, :_reduce_7,
        2, 18, :_reduce_8,
        2, 18, :_reduce_9,
        1, 18, :_reduce_10,
        3, 19, :_reduce_11,
        3, 19, :_reduce_12,
        1, 19, :_reduce_13,
        1, 20, :_reduce_14,
        2, 20, :_reduce_15,
        2, 20, :_reduce_16,
        3, 20, :_reduce_17
      ]

      racc_reduce_n = 18

      racc_shift_n = 31

      racc_token_table = {
        false => 0,
        :error => 1,
        :AND_CONDITION => 2,
        :VALUE_AND => 3,
        :OR_CONDITION => 4,
        :VALUE_OR => 5,
        :NOT_CONDITION => 6,
        :GROUP_START => 7,
        :GROUP_END => 8,
        :FIELD_WITH_COMPARISON_OP => 9,
        :ENCODED_VALUE => 10,
        :FIELD => 11,
        :NULL_FIELD => 12,
        :VALUE_WILDCARD => 13
      }

      racc_nt_base = 14

      racc_use_result_var = false

      Racc_arg = [
        racc_action_table,
        racc_action_check,
        racc_action_default,
        racc_action_pointer,
        racc_goto_table,
        racc_goto_check,
        racc_goto_default,
        racc_goto_pointer,
        racc_nt_base,
        racc_reduce_table,
        racc_token_table,
        racc_shift_n,
        racc_reduce_n,
        racc_use_result_var
      ]
      Ractor.make_shareable(Racc_arg) if defined?(Ractor)

      Racc_token_to_s_table = [
        "$end",
        "error",
        "AND_CONDITION",
        "VALUE_AND",
        "OR_CONDITION",
        "VALUE_OR",
        "NOT_CONDITION",
        "GROUP_START",
        "GROUP_END",
        "FIELD_WITH_COMPARISON_OP",
        "ENCODED_VALUE",
        "FIELD",
        "NULL_FIELD",
        "VALUE_WILDCARD",
        "$start",
        "query",
        "expression",
        "conditions",
        "condition",
        "value_expression",
        "encoded_value"
      ]
      Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

      Racc_debug_parser = false

      ##### State transition tables end #####

      # reduce 0 omitted

      module_eval(<<'.,.,', __FILE__, __LINE__ + 1)
  def _reduce_1(val, _values)
     parse_query(val)
  end
.,.,

      # reduce 2 omitted

      module_eval(<<'.,.,', __FILE__, __LINE__ + 1)
  def _reduce_3(val, _values)
     parse_conditions_and(val)
  end
.,.,

      module_eval(<<'.,.,', __FILE__, __LINE__ + 1)
  def _reduce_4(val, _values)
     parse_conditions_or(val)
  end
.,.,

      module_eval(<<'.,.,', __FILE__, __LINE__ + 1)
  def _reduce_5(val, _values)
     parse_condition_not(val)
  end
.,.,

      module_eval(<<'.,.,', __FILE__, __LINE__ + 1)
  def _reduce_6(val, _values)
     parse_condition(val)
  end
.,.,

      module_eval(<<'.,.,', __FILE__, __LINE__ + 1)
  def _reduce_7(val, _values)
     parse_conditions_group(val)
  end
.,.,

      module_eval(<<'.,.,', __FILE__, __LINE__ + 1)
  def _reduce_8(val, _values)
     parse_condition_field_with_comparison(val)
  end
.,.,

      module_eval(<<'.,.,', __FILE__, __LINE__ + 1)
  def _reduce_9(val, _values)
     parse_condition_field(val)
  end
.,.,

      module_eval(<<'.,.,', __FILE__, __LINE__ + 1)
  def _reduce_10(val, _values)
     parse_condition_null_field(val)
  end
.,.,

      module_eval(<<'.,.,', __FILE__, __LINE__ + 1)
  def _reduce_11(val, _values)
     parse_value_expression_or(val)
  end
.,.,

      module_eval(<<'.,.,', __FILE__, __LINE__ + 1)
  def _reduce_12(val, _values)
     parse_value_expression_and(val)
  end
.,.,

      module_eval(<<'.,.,', __FILE__, __LINE__ + 1)
  def _reduce_13(val, _values)
     parse_value_expression(val)
  end
.,.,

      module_eval(<<'.,.,', __FILE__, __LINE__ + 1)
  def _reduce_14(val, _values)
     parse_encoded_value(val)
  end
.,.,

      module_eval(<<'.,.,', __FILE__, __LINE__ + 1)
  def _reduce_15(val, _values)
     parse_encoded_value_wildcard(val)
  end
.,.,

      module_eval(<<'.,.,', __FILE__, __LINE__ + 1)
  def _reduce_16(val, _values)
     parse_encoded_value_wildcard(val)
  end
.,.,

      module_eval(<<'.,.,', __FILE__, __LINE__ + 1)
  def _reduce_17(val, _values)
     parse_encoded_value_wildcard(val)
  end
.,.,

      def _reduce_none(val, _values)
        val[0]
      end
    end   # class ExpressionParser
  end   # module Filtering
end   # module ApiQueryLanguage
