# frozen_string_literal: true

require "test_helper"
require "another_api/openapi"

class AnotherApi::OpenAPI::GeneratorTest < Minitest::Test
  def setup
    @prev = AnotherApi::OpenAPI.instance_variable_get(:@configuration)
    AnotherApi::OpenAPI.reset_configuration!
    AnotherApi::OpenAPI::EndpointRegistry.clear!

    AnotherApi::OpenAPI.configure do |c|
      c.title = "Test API"
      c.version = "1.0"
      c.description = "Generated by AnotherApi::OpenAPI"
      c.path_prefix = "/api/test"
      c.eager_load_controllers = false
      c.default_variant_name = :default
    end

    register_posts_index_endpoint
  end

  def teardown
    AnotherApi::OpenAPI::EndpointRegistry.clear!
    AnotherApi::OpenAPI.instance_variable_set(:@configuration, @prev)
  end

  def test_generates_3_1_spec_with_configured_info_and_servers
    spec = AnotherApi::OpenAPI::Generator.generate

    assert_equal "3.1.0", spec[:openapi]
    assert_equal "Test API", spec[:info][:title]
    assert_equal "1.0", spec[:info][:version]
    assert_equal "Generated by AnotherApi::OpenAPI", spec[:info][:description]
    assert_equal [{url: "/api/test"}], spec[:servers]
  end

  def test_generates_paths_from_endpoint_registry
    spec = AnotherApi::OpenAPI::Generator.generate

    assert spec[:paths].key?("/posts"), "Expected /posts path; got #{spec[:paths].keys.inspect}"
    operation = spec[:paths]["/posts"]["get"]
    assert_equal "List posts", operation[:summary]
    assert_equal ["Posts"], operation[:tags]
    assert operation[:responses]["200"]
    assert operation[:responses]["401"]
  end

  def test_generates_schemas_for_referenced_serializer
    spec = AnotherApi::OpenAPI::Generator.generate

    assert spec[:components][:schemas].key?("PostFull"),
      "Expected PostFull; got #{spec[:components][:schemas].keys.inspect}"
    assert spec[:components][:schemas].key?("PaginationMetadata")
  end

  def test_security_and_components_parameters_are_present
    spec = AnotherApi::OpenAPI::Generator.generate

    assert_equal [{bearerAuth: []}], spec[:security]
    assert spec[:components][:securitySchemes].key?(:bearerAuth)
    assert spec[:components][:parameters].key?(:page)
    assert spec[:components][:parameters].key?(:filter)
  end

  def test_eager_load_controllers_loads_files_matching_glob
    # Configure to actually walk a glob; point at the existing dummy
    # controllers dir which is harmless to require_dependency repeatedly.
    AnotherApi::OpenAPI.configuration.eager_load_controllers = true
    # Rails.root is the dummy app root (test/dummy), so the glob is relative to that.
    AnotherApi::OpenAPI.configuration.controllers_glob = "app/controllers/test/*_controller.rb"

    # Should not raise.
    spec = AnotherApi::OpenAPI::Generator.generate
    assert_equal "Test API", spec[:info][:title]
  end

  def test_namespace_auto_discovery_picks_up_schemas_with_matching_prefix
    AnotherApi::OpenAPI.configuration.schema_namespace_prefix = "CoreSchemas::V2::"
    # Probe variants must include :default, since that's what Post defines.
    AnotherApi::OpenAPI.configuration.additional_discovery_variants = [:default]

    spec = AnotherApi::OpenAPI::Generator.generate
    schemas = spec[:components][:schemas].keys

    assert_includes schemas, "PostFull",
      "Expected ObjectSpace auto-discovery to pick up CoreSchemas::V2::Post; got #{schemas.inspect}"
  end

  def test_endpoint_metadata_dsl_registers_via_controller
    AnotherApi::OpenAPI::EndpointRegistry.clear!

    klass = Class.new(Test::PostsController) do
      include AnotherApi::OpenAPI::EndpointMetadata

      api_resource "Posts", schema: -> { CoreSchemas::V2::Post }
      api_action :index, summary: "List via DSL"
    end
    # Force the controller_path to match the registered route by reusing
    # the parent's controller_path.
    klass.define_singleton_method(:controller_path) { "test/posts" }

    entries = AnotherApi::OpenAPI::EndpointRegistry.all
    assert_equal 1, entries.size
    assert_equal "List via DSL", entries.first.summary
    assert_equal ["Posts"], entries.first.tags
  end

  private

  def register_posts_index_endpoint
    AnotherApi::OpenAPI::EndpointRegistry.register(
      AnotherApi::OpenAPI::EndpointRegistry::Entry.new(
        controller_class: Test::PostsController,
        action: :index,
        summary: "List posts",
        tags: ["Posts"],
        schema_lambda: -> { CoreSchemas::V2::Post },
        description: "Returns posts",
        custom_path: nil,
        custom_verb: nil,
        custom_operation_id: nil,
        custom_query_params: nil
      )
    )
  end
end
